### ISSUE TITLE
Why make the way to override method exclusive?

### ISSUE THREAD

**Issue by cyjake** [expressjs/method-override#8]
AFAIK, there are at least three ways to override request method:
1. via `{ X-HTTP-METHOD-OVERRIDE: PUT }` header
2. via `?_method=PUT`
3. via `req.body._method`

In my not so complicated application which was built with express 3, there are two ways of them involved already. And as far as I can tell, we can't ditch NO. 2 and 3 completely unless the application we are implementing is totally asynchronized with JavaScript.

So why make the way to override exclusive?

**Comment by brookr** [comment]
Came here reading through old issues in search of the arguments against hiding the method in a form input (as [Rack does](https://github.com/rack/rack/blob/2-0-stable/lib/rack/method_override.rb), and therefore Sinatra and Rails). Really appreciate the background info, and am now a convert to the query string method, since that makes it visible right at the top of the raw HTTP request.
